export const seoSearchPhrases = [
  "agência de marketing digital",
  "agência de marketing digital Recife",
  "agência de marketing Recife",
  "empresa de marketing digital Recife",
  "serviços de marketing digital",
  "agência de comunicação digital",
  "agência de publicidade Recife",
  "marketing digital Recife",
  "consultoria de marketing digital",
  "consultoria de marketing Recife",
  "agência de marketing para empresas",
  "agência de marketing para pequenas empresas",
  "terceirização de marketing",
  "planejamento de marketing digital",
  "estratégia de marketing digital",
  "orçamento agência de marketing",
  "contratar agência de marketing digital",
  "agência de marketing com atendimento em Recife",
  "agência de marketing Pernambuco",
  "marketing digital para empresas Recife",
  "agência de branding",
  "agência de branding Recife",
  "consultoria de branding",
  "gestão de marca",
  "estratégia de marca",
  "posicionamento de marca",
  "criação de identidade visual",
  "identidade visual Recife",
  "rebranding de marca",
  "desenvolvimento de marca",
  "manual de identidade visual",
  "design de logotipo",
  "criação de logomarca Recife",
  "branding para pequenas empresas",
  "fortalecimento de marca",
  "gestão de redes sociais",
  "gestão de redes sociais Recife",
  "agência de redes sociais",
  "social media Recife",
  "gerenciamento de Instagram",
  "gestão de Instagram para empresas",
  "agência de Instagram",
  "planejamento de redes sociais",
  "estratégia para redes sociais",
  "criação de calendário editorial",
  "produção de conteúdo para Instagram",
  "gerenciamento de mídias sociais",
  "marketing para redes sociais",
  "aumentar engajamento no Instagram",
  "gestão de LinkedIn para empresas",
  "produção de conteúdo",
  "agência de conteúdo Recife",
  "marketing de conteúdo",
  "criação de conteúdo para empresas",
  "produção audiovisual Recife",
  "cobertura audiovisual de eventos",
  "cobertura de eventos Recife",
  "criação de vídeos para redes sociais",
  "produção de reels para empresas",
  "fotografia e vídeo para eventos",
  "roteiro para vídeos institucionais",
  "vídeo institucional para empresas",
  "conteúdo para marcas",
  "produção de conteúdo digital",
  "criação de campanha de conteúdo",
  "design gráfico Recife",
  "agência de design gráfico",
  "criação de peças gráficas",
  "design para redes sociais",
  "identidade visual para empresas",
  "design de apresentação comercial",
  "criação de material publicitário",
  "design de campanha",
  "direção de arte",
  "criação de key visual",
  "design estratégico",
  "design de marca",
  "gestão de tráfego pago",
  "tráfego pago Recife",
  "agência de tráfego pago",
  "gestor de tráfego Recife",
  "campanhas Google Ads",
  "gestão de Google Ads",
  "campanhas Meta Ads",
  "gestão de anúncios Instagram",
  "publicidade online para empresas",
  "anúncios para geração de leads",
  "campanha de conversão digital",
  "mídia paga para empresas",
  "consultoria de tráfego pago",
  "automação de marketing",
  "automação de marketing Recife",
  "sistemas e automações para empresas",
  "automação de processos",
  "integração de ferramentas digitais",
  "automação de atendimento",
  "automação de geração de leads",
  "implementação de CRM",
  "tecnologia para marketing",
  "soluções digitais personalizadas",
] as const;

export const seoKeywords = [
  "marketing digital",
  "agência de marketing",
  "agência digital",
  "comunicação digital",
  "publicidade digital",
  "estratégia digital",
  "consultoria de marketing",
  "planejamento de marketing",
  "marketing para empresas",
  "marketing local",
  "marketing Recife",
  "agência Recife",
  "marketing Pernambuco",
  "presença digital",
  "posicionamento digital",
  "branding",
  "gestão de marca",
  "estratégia de marca",
  "identidade visual",
  "identidade de marca",
  "posicionamento de marca",
  "rebranding",
  "brand design",
  "design de marca",
  "manual da marca",
  "logotipo",
  "logomarca",
  "direção de arte",
  "key visual",
  "campanha publicitária",
  "redes sociais",
  "gestão de redes sociais",
  "social media",
  "gestão de Instagram",
  "Instagram para empresas",
  "LinkedIn para empresas",
  "TikTok para empresas",
  "planejamento de conteúdo",
  "calendário editorial",
  "engajamento digital",
  "conteúdo para redes sociais",
  "produção de conteúdo",
  "marketing de conteúdo",
  "conteúdo para marcas",
  "copywriting",
  "redação publicitária",
  "roteiro de conteúdo",
  "criação de posts",
  "produção de reels",
  "vídeos para Instagram",
  "produção audiovisual",
  "vídeo institucional",
  "cobertura audiovisual",
  "cobertura de eventos",
  "fotografia de eventos",
  "vídeo para empresas",
  "conteúdo audiovisual",
  "edição de vídeo",
  "motion design",
  "storytelling de marca",
  "design gráfico",
  "design para redes sociais",
  "peças gráficas",
  "material publicitário",
  "apresentação comercial",
  "design estratégico",
  "criativos para anúncios",
  "layout para campanha",
  "identidade de campanha",
  "design Recife",
  "tráfego pago",
  "gestão de tráfego",
  "Google Ads",
  "Meta Ads",
  "Instagram Ads",
  "Facebook Ads",
  "mídia paga",
  "anúncios online",
  "campanha de conversão",
  "geração de leads",
  "performance digital",
  "remarketing",
  "funil de vendas",
  "campanha de leads",
  "otimização de anúncios",
  "automação de marketing",
  "automação de processos",
  "automação de atendimento",
  "integração de sistemas",
  "implementação de CRM",
  "CRM para empresas",
  "tecnologia para marketing",
  "soluções digitais",
  "sistemas personalizados",
  "chatbot para empresas",
  "integração de CRM",
  "experiência de marca",
  "ativação de marca",
  "marketing B2B",
  "marketing para pequenas empresas",
] as const;

export type SeoCatalogTab = "phrases" | "keywords";

export type SeoCatalogGroup = {
  readonly id: string;
  readonly title: string;
  readonly terms: readonly string[];
};

export const seoSearchGroups: readonly SeoCatalogGroup[] = [
  {
    id: "strategy",
    title: "Agência e estratégia",
    terms: seoSearchPhrases.slice(0, 20),
  },
  {
    id: "branding",
    title: "Branding e gestão de marca",
    terms: seoSearchPhrases.slice(20, 35),
  },
  {
    id: "social",
    title: "Redes sociais",
    terms: seoSearchPhrases.slice(35, 50),
  },
  {
    id: "content",
    title: "Conteúdo e audiovisual",
    terms: seoSearchPhrases.slice(50, 65),
  },
  {
    id: "design",
    title: "Design gráfico",
    terms: seoSearchPhrases.slice(65, 77),
  },
  {
    id: "media",
    title: "Tráfego pago",
    terms: seoSearchPhrases.slice(77, 90),
  },
  {
    id: "technology",
    title: "Sistemas e automações",
    terms: seoSearchPhrases.slice(90, 100),
  },
];

export const seoKeywordGroups: readonly SeoCatalogGroup[] = [
  {
    id: "strategy",
    title: "Agência e estratégia",
    terms: seoKeywords.slice(0, 15),
  },
  {
    id: "branding",
    title: "Branding e gestão de marca",
    terms: seoKeywords.slice(15, 30),
  },
  {
    id: "social",
    title: "Redes sociais",
    terms: seoKeywords.slice(30, 41),
  },
  {
    id: "content",
    title: "Conteúdo e audiovisual",
    terms: seoKeywords.slice(41, 61),
  },
  {
    id: "design",
    title: "Design gráfico",
    terms: seoKeywords.slice(61, 71),
  },
  {
    id: "media",
    title: "Tráfego pago",
    terms: seoKeywords.slice(71, 86),
  },
  {
    id: "technology",
    title: "Sistemas e automações",
    terms: seoKeywords.slice(86, 97),
  },
  {
    id: "experiences",
    title: "Experiências e segmentos",
    terms: seoKeywords.slice(97, 100),
  },
];
